name = "station-count"
main = "src/index.js"
compatibility_date = "2024-11-01"
send_metrics = true

[[d1_databases]]
binding = "DATABASE"
database_name = "stations"
database_id = "ab8a288d-ab6a-49d6-a7e2-ac51d24b376c"