name = "stations"
main = "src/entry.py"
compatibility_flags = ["python_workers"]
compatibility_date = "2024-11-01"

[[d1_databases]]
binding = "DB"
database_name = "stations"
database_id = "ab8a288d-ab6a-49d6-a7e2-ac51d24b376c"