name = "webinterface-cf"
compatibility_date = "2024-11-01"
send_metrics = true
pages_build_output_dir = "/"

[env.production]
d1_databases = [
    { binding = "DATABASE", database_name = "stations", database_id = "ab8a288d-ab6a-49d6-a7e2-ac51d24b376c" },
]

[env.preview]
d1_databases = [
    { binding = "DATABASE", database_name = "stations-staging", database_id = "3939b97c-932c-4176-9360-31c81614104d" },
]